# Generated by Django 5.2 on 2025-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
