# Generated by Django 5.2 on 2025-04-27 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_city_title_region_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='location',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='location',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
