# Generated by Django 5.2 on 2025-04-27 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_city_location_alter_region_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='video',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='video',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='location',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='location',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
