# Generated by Django 5.2 on 2025-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='region_images/'),
        ),
    ]
